name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os:  [
          ubuntu-latest, 
#          debian-11, debian-10, debian-9, debian-8,
#          fedora-39, fedora-38, fedora-37, fedora-36,  # Fedora
#          centos-stream-9, centos-stream-8, rocky-linux-8, ubuntu-20.04,
          rocky-linux-9 # RHEL-likes
        ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies (${{ matrix.os }}) # OS-specific dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y linux-headers-generic
          elif [[ "${{ matrix.os }}" == "ubuntu-20.04" ]]; then
            sudo apt-get update
            sudo apt-get install -y linux-headers-$(uname -r)
          elif [[ "${{ matrix.os }}" == "ubuntu-18.04" ]]; then
            sudo apt-get update
            sudo apt-get install -y linux-headers-$(uname -r)
          elif [[ "${{ matrix.os }}" == "debian-11" ]]; then
            sudo apt-get update
            sudo apt-get install -y linux-headers-$(uname -r)
          elif [[ "${{ matrix.os }}" == "debian-10" ]]; then
            sudo apt-get update
            sudo apt-get install -y linux-headers-$(uname -r)
          elif [[ "${{ matrix.os }}" == "debian-9" ]]; then
            sudo apt-get update
            sudo apt-get install -y linux-headers-$(uname -r)
          elif [[ "${{ matrix.os }}" == "debian-8" ]]; then
            sudo apt-get update
            sudo apt-get install -y linux-headers-$(uname -r)
          elif [[ "${{ matrix.os }}" == "fedora-39" || "${{ matrix.os }}" == "fedora-38" || "${{ matrix.os }}" == "fedora-37" || "${{ matrix.os }}" == "fedora-36" ]]; then  # Fedora
            sudo dnf -y install kernel-headers
            # Fedora often needs development tools
            sudo dnf -y groupinstall "Development Tools"
          elif [[ "${{ matrix.os }}" == "centos-stream-9" || "${{ matrix.os }}" == "centos-stream-8" || "${{ matrix.os }}" == "rocky-linux-9" || "${{ matrix.os }}" == "rocky-linux-8" ]]; then  # RHEL-likes
            sudo dnf -y install kernel-devel # Use kernel-devel on RHEL-based
            sudo dnf -y groupinstall "Development Tools" # Often needed
          fi
      - name: Make (${{ matrix.os }})
        run: make
      - name: rename 
        run: mv diamorphine.ko diamorphine-${{ matrix.os }}
      - name: Upload Artifacts (${{ matrix.os }})
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: diamorphine-${{ matrix.os }} # Replace with the actual path


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Important!
        with:
          tag_name: ${{ github.ref }} # The tag that triggered the workflow
          release_name: Release ${{ github.ref }} # Name of the release
          body: | # Release notes (can be multiline)
            Changes in this release:
            - Bug fixes
            - New features

  
      - name: Upload Release Asset (Binary)
        id: upload_binary
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Important!
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # URL from create-release step
          asset_path: .\diamorphine-${{ matrix.os }} 
          asset_name: diamorphine-${{ matrix.os }}_${{ github.ref }}.tar.gz
  
      - name: Upload Release Asset (Source Code - Optional)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./diamorphine-${{ matrix.os }}-${{ github.ref }}.tar.gz # Path to your source archive
          asset_name: diamorphine-${{ matrix.os }}-${{ github.ref }}.tar.gz # Name of source archive